/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPaywallStatus {
  'principal' : Principal,
  'paywallStatus' : PaywallStatus,
  'totalStorage' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface File {
  'id' : FileId,
  'content' : ExternalBlob,
  'displayName' : string,
  'owner' : Principal,
  'cryptedSymmetricKey' : [] | [Uint8Array],
  'description' : string,
  'sharedWith' : Array<Principal>,
}
export type FileId = string;
export interface FileSub {
  'id' : FileId,
  'displayName' : string,
  'owner' : Principal,
  'cryptedSymmetricKey' : [] | [Uint8Array],
  'description' : string,
  'sharedWith' : Array<Principal>,
}
export interface Note {
  'id' : NoteId,
  'title' : string,
  'content' : string,
  'owner' : Principal,
  'cryptedSymmetricKey' : [] | [Uint8Array],
  'sharedWith' : Array<Principal>,
}
export type NoteId = string;
export interface NoteSub {
  'id' : NoteId,
  'title' : string,
  'owner' : Principal,
  'cryptedSymmetricKey' : [] | [Uint8Array],
  'sharedWith' : Array<Principal>,
}
export interface PaywallStatus {
  'hasPaid' : boolean,
  'planLabel' : [] | [string],
  'paidUntil' : [] | [bigint],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNote' : ActorMethod<[string, string], NoteId>,
  'deleteFile' : ActorMethod<[FileId], undefined>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'getAllAdminPaywallStates' : ActorMethod<[], Array<AdminPaywallStatus>>,
  'getCallerPaywallStatus' : ActorMethod<[], PaywallStatus>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[FileId], File>,
  'getMySharedWithMe' : ActorMethod<[], Array<string>>,
  'getPaywallStatus' : ActorMethod<[Principal], PaywallStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFiles' : ActorMethod<[], Array<FileSub>>,
  'listNotes' : ActorMethod<[], Array<NoteSub>>,
  'readNote' : ActorMethod<[NoteId], Note>,
  'revokeAccess' : ActorMethod<[string, string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPaywallStatus' : ActorMethod<
    [Principal, boolean, [] | [string], [] | [bigint]],
    undefined
  >,
  'shareItem' : ActorMethod<[string, string, Principal], undefined>,
  'updateFileMetadata' : ActorMethod<[FileId, string, string], undefined>,
  'updateNote' : ActorMethod<[NoteId, string, string], undefined>,
  'uploadFile' : ActorMethod<[string, ExternalBlob], FileId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];