/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NoteId = IDL.Text;
export const FileId = IDL.Text;
export const PaywallStatus = IDL.Record({
  'hasPaid' : IDL.Bool,
  'planLabel' : IDL.Opt(IDL.Text),
  'paidUntil' : IDL.Opt(IDL.Nat),
});
export const AdminPaywallStatus = IDL.Record({
  'principal' : IDL.Principal,
  'paywallStatus' : PaywallStatus,
  'totalStorage' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const File = IDL.Record({
  'id' : FileId,
  'content' : ExternalBlob,
  'displayName' : IDL.Text,
  'owner' : IDL.Principal,
  'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'description' : IDL.Text,
  'sharedWith' : IDL.Vec(IDL.Principal),
});
export const FileSub = IDL.Record({
  'id' : FileId,
  'displayName' : IDL.Text,
  'owner' : IDL.Principal,
  'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'description' : IDL.Text,
  'sharedWith' : IDL.Vec(IDL.Principal),
});
export const NoteSub = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'sharedWith' : IDL.Vec(IDL.Principal),
});
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'sharedWith' : IDL.Vec(IDL.Principal),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
  'deleteFile' : IDL.Func([FileId], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'getAllAdminPaywallStates' : IDL.Func(
      [],
      [IDL.Vec(AdminPaywallStatus)],
      ['query'],
    ),
  'getCallerPaywallStatus' : IDL.Func([], [PaywallStatus], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([FileId], [File], ['query']),
  'getMySharedWithMe' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPaywallStatus' : IDL.Func([IDL.Principal], [PaywallStatus], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFiles' : IDL.Func([], [IDL.Vec(FileSub)], ['query']),
  'listNotes' : IDL.Func([], [IDL.Vec(NoteSub)], ['query']),
  'readNote' : IDL.Func([NoteId], [Note], ['query']),
  'revokeAccess' : IDL.Func([IDL.Text, IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaywallStatus' : IDL.Func(
      [IDL.Principal, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'shareItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Principal], [], []),
  'updateFileMetadata' : IDL.Func([FileId, IDL.Text, IDL.Text], [], []),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
  'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [FileId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NoteId = IDL.Text;
  const FileId = IDL.Text;
  const PaywallStatus = IDL.Record({
    'hasPaid' : IDL.Bool,
    'planLabel' : IDL.Opt(IDL.Text),
    'paidUntil' : IDL.Opt(IDL.Nat),
  });
  const AdminPaywallStatus = IDL.Record({
    'principal' : IDL.Principal,
    'paywallStatus' : PaywallStatus,
    'totalStorage' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const File = IDL.Record({
    'id' : FileId,
    'content' : ExternalBlob,
    'displayName' : IDL.Text,
    'owner' : IDL.Principal,
    'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'description' : IDL.Text,
    'sharedWith' : IDL.Vec(IDL.Principal),
  });
  const FileSub = IDL.Record({
    'id' : FileId,
    'displayName' : IDL.Text,
    'owner' : IDL.Principal,
    'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'description' : IDL.Text,
    'sharedWith' : IDL.Vec(IDL.Principal),
  });
  const NoteSub = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'sharedWith' : IDL.Vec(IDL.Principal),
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'cryptedSymmetricKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'sharedWith' : IDL.Vec(IDL.Principal),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
    'deleteFile' : IDL.Func([FileId], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'getAllAdminPaywallStates' : IDL.Func(
        [],
        [IDL.Vec(AdminPaywallStatus)],
        ['query'],
      ),
    'getCallerPaywallStatus' : IDL.Func([], [PaywallStatus], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([FileId], [File], ['query']),
    'getMySharedWithMe' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPaywallStatus' : IDL.Func([IDL.Principal], [PaywallStatus], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFiles' : IDL.Func([], [IDL.Vec(FileSub)], ['query']),
    'listNotes' : IDL.Func([], [IDL.Vec(NoteSub)], ['query']),
    'readNote' : IDL.Func([NoteId], [Note], ['query']),
    'revokeAccess' : IDL.Func([IDL.Text, IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaywallStatus' : IDL.Func(
        [IDL.Principal, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'shareItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Principal], [], []),
    'updateFileMetadata' : IDL.Func([FileId, IDL.Text, IDL.Text], [], []),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
    'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [FileId], []),
  });
};

export const init = ({ IDL }) => { return []; };